### ISSUE TITLE
Error filling in template 'validation_encryption.yml.erb'

### ISSUE THREAD

**Issue by sabarivijayan-fd** [pivotal/credhub-release#49]
What version of the credhub server you are using?
2.4.0

What version of the credhub cli you are using?
not deployed yet

If you were attempting to accomplish a task, what was it you were attempting to do?
installing credhub along with concourse

What did you expect to happen?
successful deployment

What was the actual behavior?
getting deployment failures as below 
 L Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'web'. Errors are:
    - Unable to render templates for job 'credhub'. Errors are:
      - Error filling in template 'drain.erb' (line 9: undefined method `[]' for nil:NilClass)
      - Error filling in template 'validation_encryption.yml.erb' (line 59: `provider_name` provided for key is not in list of providers)
Please confirm where necessary:
* [yes ] I have included a log output
* [ yes] My log includes an error message
* [ yes] I have included steps for reproduction

part of manifest file :
      credhub:
        authentication:
          uaa:
            ca_certs:
            - ((tls_cert))
            url: https://((concourse_host_name)):8443
            verification_key: ((uaa-jwt.public_key))
        authorization:
          permissions:
          - path: /
            actors:
            - uaa-user:credhub_cli
            operations:
            - read
            - write
            - delete
            - read_acl
            - write_acl
        data_storage:
          database: credhub
          password: ((credhub-db-password))
          require_tls: false
          type: postgres
          username: credhub
        encryption:
          keys:
          - active: true
          - key_properties:
              provider_name: test
              encryption_password: ((credhub-encryption-password))
          providers:
          - name: internal-provider
            type: internal
          - name: test
            type: internal

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by zafai** [comment]
@sabarivijayan-fd We had the same problem today, our solution was too explicitly disable ACL.

Search for `authorization:` in your manifest and replace it with this:
Of course, you need to add the indent. 

> authorization:
>           acls:
>             enabled: false

**Comment by sabarivijayan-fd** [comment]
Hi Zafai,
               i updated manifest as per your suggestion and getting same error.
               error seems to be provider_name is not getting resolved from manifest though it is available. Please let me know your inputs.

                   **L Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'web'. Errors are:
    - Unable to render templates for job 'credhub'. Errors are:
      - Error filling in template 'drain.erb' (line 9: undefined method `[]' for nil:NilClass)
      - Error filling in template 'validation_encryption.yml.erb' (line 59: `provider_name` provided for key is not in list of providers)
Task 60 | 05:03:13 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'web'. Errors are:
    - Unable to render templates for job 'credhub'. Errors are:
      - Error filling in template 'drain.erb' (line 9: undefined method `[]' for nil:NilClass)
      - Error filling in template 'validation_encryption.yml.erb' (line 59: `provider_name` provided for key is not in list of providers)**

**Comment by zafai** [comment]
Could you provide your Manifest over this tool https://codebeautify.org/yaml-validator 
so that the yaml format does not get lost when sharing?

**Comment by sabarivijayan-fd** [comment]
Please find below credhub.yml
---

- type: replace
  path: /instance_groups/name=web/jobs/name=uaa/properties/uaa/clients?
  value:
    concourse_to_credhub:
      access-token-validity: 1200
      authorities: credhub.read,credhub.write
      authorized-grant-types: client_credentials
      override: true
      refresh-token-validity: 3600
      scope: ""
      secret: ((concourse_to_credhub_secret))
    credhub_cli:
      access-token-validity: 1200
      authorities: uaa.resource
      authorized-grant-types: password,refresh_token
      override: true
      refresh-token-validity: 3600
      scope: credhub.read,credhub.write
      secret: ""

- type: replace
  path: /instance_groups/name=web/jobs/name=uaa/properties/uaa/scim/users/0/groups/-
  value:
    credhub.read
- type: replace
  path: /instance_groups/name=web/jobs/name=uaa/properties/uaa/scim/users/0/groups/-
  value:
    credhub.write

- type: replace
  path: /instance_groups/name=web/jobs/-
  value:
    name: credhub
    properties:
      credhub:
        authentication:
          uaa:
            ca_certs:
            - ((tls_cert))
            url: https://((concourse_host_name)):8443
            verification_key: ((uaa-jwt.public_key))
        authorization:
            acls:
                enabled: false
        data_storage:
          database: credhub
          password: ((credhub-db-password))
          require_tls: false
          type: postgres
          username: credhub
        encryption:
          keys:
          - active: true
          - key_properties:
              provider_name: test
              encryption_password: ((credhub-encryption-password))
          providers:
          - name: internal-provider
            type: internal
          - name: test
            type: internal
        port: 8844
        tls: 
          certificate: ((tls_cert))
          private_key: ((tls_key))
    release: credhub

- type: replace
  path: /instance_groups/name=db/jobs/name=postgres/properties/databases/databases/-
  value:
    name: credhub

- type: replace
  path: /instance_groups/name=db/jobs/name=postgres/properties/databases/roles/-
  value:
    name: credhub
    password: ((credhub-db-password))

- type: replace
  path: /releases/-
  value:
    name: credhub
    version: ((credhub_version))

- type: replace
  path: /variables/-
  value:
    name: credhub-db-password
    type: password

- type: replace
  path: /variables/-
  value:
    name: credhub-encryption-password
    options:
      length: 40
    type: password

- type: replace
  path: /variables/-
  value:
    name: concourse_to_credhub_secret
    type: password

**Comment by sabarivijayan-fd** [comment]
[credhubyml.txt](https://github.com/pivotal/credhub-release/files/3901643/credhubyml.txt)
attached file for your reference

**Comment by ankeesler** [comment]
@sabarivijayan-fd - when I look at the above `credhubyml.txt` file, it looks like you need to move your `provider_name` key up a level, as a key in the same map as `credhub.encryption.keys.active`.

Here is an example that you can follow: https://github.com/pivotal/credhub-release/blob/2.4.0/jobs/credhub/spec#L112-L114.

Please reopen if you have more questions.
