### ISSUE TITLE
JwtAccessTokenConverter: Unable to create an RSA verifier from verifierKey

### ISSUE THREAD

**Issue by sabarivijayan-fd** [pivotal/credhub-release#50]
What version of the credhub server you are using?
2.4.0

What version of the credhub cli you are using?
Not Installed

If you were attempting to accomplish a task, what was it you were attempting to do?
we have started deploying concourse along with UAA and Credhub bosh release (both UAA and credhub are colocated in Concourse Web VM).
concourse Web and UAA got deployed successfully but credhub job is in failed state.

What did you expect to happen?
successful deployment of credhub

What was the actual behavior?

credhub job is in failed state
Please confirm where necessary:
 [Yes ] I have included a log output
 [Yes ] My log includes an error message
 [Yes
[credhub.log](https://github.com/pivotal/credhub-release/files/3932313/credhub.log)
 ] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/) 

looking forward to your input.

**Comment by ankeesler** [comment]
@sabarivijayan-fd - thank you for attaching that credhub.log file, that is very helpful. I do see the `JwtAccessTokenConverter` error that you mentioned. I also see a lot of errors around that look a little something like this: `java.lang.IllegalArgumentException: Invalid JWK Set URL: no protocol: null/token_keys`. CredHub's JWK URL should be UAA's URL. Can you verify that your `credhub.authentication.uaa.internal_url` and `credhub.authentication.uaa.url` CredHub properties are set to the correct URL for UAA?

**Comment by sabarivijayan-fd** [comment]
Hi ankeesler ,
 i set correct url for UAA and credhub JWK Url, issue got resolved, thanks for your help.
