### ISSUE TITLE
Feature request: Support for concatenated database CA certs 

### ISSUE THREAD

**Issue by peterellisjones** [pivotal/credhub-release#54]
Hi Credhub team,

A typical way rotate certificates for a distributed system is to deploy it in the following three phases:
1. Servers use the _old_ leaf certs and clients trust the _new and old_ CA certs
2. Servers use the _new_ leaf certs and clients trust the _new and old_ CA certs
3. Servers use the _new_ leaf certs and clients trust only the _new_ CA certs

To allow clients to trust both old and new CA certs at the same time you have to allow multiple concatenated PEM-encoded certificates in the CA variables. 

Currently the following line:
https://github.com/pivotal/credhub-release/blob/f5a33235c956de3affb445ce870c1744939a2ffe/jobs/credhub/templates/init_key_stores.erb#L60-L66

Does not support concatenated PEM-encoded certificates for the database CA property (`data_storage.tls_ca`), meaning it is impossible to rotate certificates using this strategy for Credhub.

kind regards,

Pete

**Comment by LizClaireMorris** [comment]
Hi @peterellisjones, thanks for bringing this to our attention. We'll look into this and validate it soon.

**Comment by ankeesler** [comment]
@peterellisjones - thank you again for reporting. This should be fixed as of https://github.com/pivotal/credhub-release/commit/77f92de344265985517798b8295b78e7e2d6956c. Please let us know if this continues to be an issue. Thank you.
