### ISSUE TITLE
log4j 2.16.x DOS vuln

### ISSUE THREAD

**Issue by thelangley** [pivotal/credhub-release#63]
Already fixed in source https://github.com/cloudfoundry/credhub/commit/468c6be7d3e84780399c8f5c0bfc35997f1e46dc but no release to match

Could 2.12.0 be released and we'll run it through our pipelines?

**Comment by riddhichheda** [comment]
+1

**Comment by jiama-svmx** [comment]
> Already fixed in source [cloudfoundry/credhub@468c6be](https://github.com/cloudfoundry/credhub/commit/468c6be7d3e84780399c8f5c0bfc35997f1e46dc) but no release to match
> 
> Could 2.12.0 be released and we'll run it through our pipelines?

any ETA on this?

**Comment by thelangley** [comment]
https://github.com/cloudfoundry/credhub/commit/b61a12d7676670cbb0b925a67a6df61367c7a2ed made recently to bump to 2.17.1

could a release please be made including these changes?

**Comment by thelangley** [comment]
https://github.com/pivotal/credhub-release/releases/tag/2.11.1 has happened :)

Thanks everyone
